#!/bin/bash
# Get the youtube video title and store it in a variable.
videoTitle=$(youtube-dl $1 --get-title)
# mkdir is allergic to spaces :) .
# delete spaces from video title variable
cleanVideoTitle1=${videoTitle// /_}
# mkdir will see backslash as a whole new directory to be navigated.
# delete backslashes from video title variable
cleanVideoTitle2=${cleanVideoTitle1//'/'/_}
# mkdir and cd don't like the dollar sign listed in the directory name.
# delete dollar sign from video title variable
cleanVideoTitle3=${cleanVideoTitle2//'$'/_}
# declare most variables in an associative array for later use in the script
declare -A main=( [url]=$1 [type]=$2 [cleanVideoTitle]=$cleanVideoTitle3 [workingDirectory]=$(pwd) )

function mp3_single_function {

    title_name=${main[cleanVideoTitle]}'_Audio'
    mkdir ${main[workingDirectory]}/$title_name
    cd $title_name
    youtube-dl -cwix -r 10M --no-playlist -f "bestaudio/best" -o "%(title)s.%(ext)s" --audio-quality 0 --audio-format mp3 --embed-thumbnail --add-metadata  ${main[url]}
    cd ${main[workingDirectory]}
    echo "The mp3 file has been downloaded to" $title_name "directory."

}

function mp3_list_function {

    title_date=$(date +'%D_%H_%M_%S')'_mp3_list'
    title_conversion=${title_date//'/'/_}
    title_conversion1=${title_conversion//':'/_}
    mkdir ${main[workingDirectory]}/$title_conversion1
    cd $title_conversion1
    youtube-dl -cwix -r 10M -f "bestaudio/best" --yes-playlist -ciw -o "%(title)s.%(ext)s" --audio-quality 0 --audio-format mp3 --embed-thumbnail --add-metadata  ${main[url]}
    cd ${main[workingDirectory]}
    echo "The mp3 list has been downloaded to " $title_conversion1 "directory"

}

function mp4_function {

    title_name=${main[cleanVideoTitle]}'_Video'
    mkdir ${main[workingDirectory]}/$title_name
    cd $title_name
    youtube-dl -cwi -r 10M -f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/bestvideo+bestaudio' --merge-output-format mp4 --embed-thumbnail --add-metadata -o '%(title)s.%(ext)s' ${main[url]}
    cd ${main[workingDirectory]}
    echo "The video has been downloaded to " $title_name "directory"
}
case ${main[type]} in

    mp3-single)
        mp3_single_function
        ;;

    mp3-list)
        mp3_list_function
        ;;

    mp4)
        mp4_function
        ;;
    both)
        mp4_function
        mp3_single_function
        ;;
  *)
    echo "Please check that you passed the correct arguments to the script!"
    echo "youtube-dl-mp4-mp3 <YOUTUBE_VIDEO_URL> <TYPE>"
    echo "Try again"
    ;;
esac
unset main
exit 1
