#!/bin/bash

# Update youtube-dl script!
youtube-dl -U
# Get the youtube video title and store it in a variable.
videoTitle=$(youtube-dl -e -s --no-playlist $1)
# Due to that some programs that this script rely on are allergic to some special characters the following line will replace them with underscores
videoTitleFormat=${videoTitle//[\'\-\.\(\)\$\!\%\&\*\#\|\"\`\ \&\:\-\–\,]/_}
# declare most variables in associative arrays.
declare -A lists=([mp3List]=$(date +'%D_%H_%M_%S')'_mp3_list' [mp4List]=$(date +'%D_%H_%M_%S')'_mp4_list' [Mp3List]=${lists[mp3List]//[\/\:]/_} [Mp4List]=${lists[mp4List]//[\/\:]/_})
declare -A singles=( [videoTitle]=$videoTitleFormat'_Video' [audioTitle]=$videoTitleFormat'_Audio' )
declare -A main=( [url]=$1 [type]=$2 [workingDirectory]=$(pwd) [cleanVideoTitle]=$videoTitleFormat )

function mp3_single_function {

    mkdir ${main[workingDirectory]}/${singles[audioTitle]}
    cd ${singles[audioTitle]}
    youtube-dl -cwix --http-chunk-size 10M -r 10M --no-playlist --restrict-filenames -f "bestaudio/best" -o "%(title)s.%(ext)s" --audio-quality 0 --audio-format mp3 --embed-thumbnail --add-metadata  ${main[url]}
    cd ${main[workingDirectory]}
    echo "The mp3 file has been downloaded to the following directory: " ${singles[audioTitle]}

}

function mp3_list_function {

#   local titleDate=${titles[mp3List]//[\/\:]/_}
    mkdir ${main[workingDirectory]}/${lists[Mp3List]}
    cd ${lists[Mp3List]}
    youtube-dl -cwix --http-chunk-size 10M -r 10M --restrict-filenames -f "bestaudio/best" --yes-playlist -ciw -o "%(title)s.%(ext)s" --audio-quality 0 --audio-format mp3 --embed-thumbnail --add-metadata  ${main[url]}
    cd ${main[workingDirectory]}
    echo "The mp3 list has been downloaded to the following directory: " ${lists[Mp3List]}

}

function mp4_list_function {

#   local titleDate=${titles[mp4List]//[\/\:]/_}
    mkdir ${main[workingDirectory]}/${lists[Mp4List]}
    cd ${lists[Mp4List]}
    youtube-dl -cwi --http-chunk-size 10M -r 10M --restrict-filenames --yes-playlist -f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/bestvideo+bestaudio' --merge-output-format mp4 --embed-thumbnail --add-metadata -o '%(title)s.%(ext)s' ${main[url]}
    cd ${main[workingDirectory]}
    echo "The videos playlist has been downloaded to the following directory: " ${lists[Mp4List]}
}

function mp4_single_function {

    mkdir ${main[workingDirectory]}/${singles[videoTitle]}
    cd ${singles[videoTitle]}
    youtube-dl -cwi --http-chunk-size 10M -r 10M --restrict-filenames --no-playlist -f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/bestvideo+bestaudio' --merge-output-format mp4 --embed-thumbnail --add-metadata -o '%(title)s.%(ext)s' ${main[url]}
    cd ${main[workingDirectory]}
    echo "The video has been downloaded to following directory: " ${singles[videoTitle]}
}

case ${main[type]} in

    mp3-single)
        mp3_single_function
        ;;
    mp4-single)
        mp4_single_function
        ;;
    mp3-list)
        mp3_list_function
        ;;
    mp4-list)
        mp4_list_function
        ;;
    both)
        mp4_single_function
        mp3_single_function
        ;;
  *)
    echo "Please check that you passed the correct arguments to the script!"
    echo "youtube-dl-mp4-mp3 <YOUTUBE_VIDEO_URL> <TYPE>"
    echo "Try again"
    ;;
esac
unset main
unset lists
unset singles
exit 1
